// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconCss: typeof import('./src/components/icons/IconCss.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconHtml: typeof import('./src/components/icons/IconHtml.vue')['default']
    IconJavascript: typeof import('./src/components/icons/IconJavascript.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconTypescript: typeof import('./src/components/icons/IconTypescript.vue')['default']
    IconVite: typeof import('./src/components/icons/IconVite.vue')['default']
    IconVuejs: typeof import('./src/components/icons/IconVuejs.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
